/* St. Augustine, 7-9 Aug 2026. Public repo: no bookings, no lodging name, no household detail. */
window.TRIP = {
  title: 'St. ', accent: 'Augustine', eyebrow: "Ship's log \u00b7 1565",
  lat: 29.8947, lng: -81.3145, tz: 'America/New_York',
  days: [
  { id: 'fri', label: 'Fri \u00b7 day one',
    note: 'Eat first, park once, then the trolley before service ends. Everything after 4:30 is one straight walk north to south and back.',
    stops: [
    { t: '11:00', key: 1, tags: ['food'], name: "Georgie's Diner", type: 'Breakfast \u00b7 pancake house',
      what: 'Retro diner. French toast, skillets, eggs, huge tots. Free parking out back.',
      blurb: 'Breakfast served until 3, kids menu, oldies on the speakers, and a lot of food for the price. Its own lot means no parking hunt while you are still hungry.',
      hours: '7:00 AM \u2013 3:00 PM daily', price: '$ \u00b7 big portions', rating: '4.5', count: '3,011',
      addr: '100 Malaga St', phone: '9048199006', q: 'Georgies Diner St Augustine',
      pid: 'ChIJywhop-sn5IgR2FX_DJgy8w8', lat: 29.892076, lng: -81.3207231, walk: '5-min drive', dur: '60 min',
      alts: [{ n: "B&B's Brunch Bar", d: 'Fruity pancakes, shrimp and grits \u00b7 7\u20132 \u00b7 4.6 (513)', q: 'B&Bs Brunch Bar St Augustine', id: 'ChIJp7KZETkn5IgRMsZsninA8M4' },
        { n: 'Metro Diner', d: 'Cinnamon-roll pancakes, fried chicken \u00b7 7 AM\u20138 PM \u00b7 4.6 (4,842)', q: 'Metro Diner St Augustine', id: 'ChIJtYj1F_En5IgRKH8T72xe5Oo' },
        { n: 'The Blue Hen Caf\u00e9', d: 'Biscuits, peach butter \u00b7 8\u20132 \u00b7 4.7 (1,965)', q: 'Blue Hen Cafe St Augustine', id: 'ChIJH7dYtJQn5IgRjdC01e4dt00' }] },

    { t: '12:15', tags: ['logistics'], name: 'Drop bags \u00b7 park once', type: 'Home base',
      what: 'Leave the car downtown for the weekend. You will not need it again.',
      blurb: 'Everything from the fort to the marina is inside a 15-minute walk. Park once near Castillo Drive and the rest of the trip is on foot.',
      hours: '\u2014', price: 'Garage $20 per entry, or hotel valet', addr: 'Castillo Dr, downtown',
      q: 'Historic Downtown Parking Garage St Augustine', lat: 29.8992, lng: -81.3158, walk: 'drive', dur: '20 min' },

    { t: '1:15', key: 1, tags: ['kids', 'history'], name: 'Old Town Trolley', type: 'The fun one \u00b7 do it first',
      what: '90-min narrated loop, open air. Stop 2 is on Castillo Dr.',
      blurb: 'The whole city without walking it, during the hottest part of the day. Stay on for the full loop the first time \u2014 you will know where everything is afterwards.',
      hours: '9:00 AM \u2013 4:30 PM \u00b7 last trolley out 4:30',
      price: 'About $34\u201340 adult \u00b7 3 and under free \u00b7 includes History Museum and the Beach Bus',
      rating: '4.6', count: '10,155', addr: 'Stop 2, Visitor Center, 10 W Castillo Dr', phone: '9048293800',
      q: 'Old Town Trolley Tours St Augustine', pid: 'ChIJBxIdDsgn5IgRgGwG3J1ZDdE',
      lat: 29.8989, lng: -81.316, walk: '1 min', dur: '90 min',
      flag: 'Hard cutoff \u2014 board by 2:30 or the loop will not finish before service ends.' },

    { t: '3:00', key: 1, tags: ['kids', 'history'], name: 'Pirate &amp; Treasure Museum', type: 'Kids first',
      what: 'Air-conditioned, treasure hunt, a cannon the kids can fire.',
      blurb: '800-plus artifacts crammed into every corner, with a scavenger hunt that keeps small kids moving and a prize at the end. Best indoor stop in town at 3 PM in August.',
      hours: '10:00 AM \u2013 7:00 PM', price: 'About $48 for a family of four', rating: '4.6', count: '4,091',
      addr: '12 S Castillo Dr', phone: '9048191444', q: 'St Augustine Pirate Treasure Museum',
      pid: 'ChIJhWfXcr4n5IgR1WRYtp4Qd7w', lat: 29.897017, lng: -81.312966, walk: '2-min walk', dur: '60\u201390 min' },

    { t: '4:20', opt: 1, tags: ['coffee', 'rest'], name: 'Crucial Coffee', type: 'Coffee stop',
      what: 'Tiny shop across from the fort. Coffee, pastries, ice cream, beer.',
      blurb: 'Shaded outdoor seating under string lights, two minutes from the museum door.',
      hours: '8:00 AM \u2013 10:00 PM Fri', price: '$', rating: '4.2', count: '577',
      addr: '26 Charlotte St', q: 'Crucial Coffee Cafe St Augustine', pid: 'ChIJjaD_-70n5IgR-ljhOe5Ei2k',
      lat: 29.8958752, lng: -81.3119831, walk: '3-min walk', dur: '20 min',
      alts: [{ n: 'The Kookaburra', d: 'Australian coffee and meat pies \u00b7 6:30 AM\u20139 PM \u00b7 4.6 (1,467)', q: 'The Kookaburra Downtown St Augustine', id: 'ChIJs-j0fpYn5IgRDCh5tKV1Obc' },
        { n: 'Southern Grounds', d: 'Big shaded patio \u00b7 6:30 AM\u20139 PM \u00b7 4.6 (289)', q: 'Southern Grounds St Augustine', id: 'ChIJz_T1MVEn5IgR19aVkOphoh0' }] },

    { t: '4:45', opt: 1, tags: ['rest'], name: 'Check in \u00b7 pool', type: 'Rest stop',
      what: 'Swim, dry clothes, slow down.',
      blurb: 'Everything from here is a short walk, so this is the moment to rest rather than push through.',
      hours: '\u2014', price: '\u2014', addr: 'Downtown', q: 'Castillo Dr St Augustine',
      lat: 29.8992, lng: -81.3158, walk: '\u2014', dur: '60 min' },

    { t: '5:45', tags: ['kids', 'free'], name: 'Project Swing playground', type: 'Free \u00b7 kids',
      what: 'Castle-themed wooden playground, fully shaded, one entrance.',
      blurb: 'Separate areas for big and small kids, a covered pavilion with benches in the middle, and it has cooled off by evening.',
      hours: '7:30 AM \u2013 7:00 PM', price: 'Free', rating: '4.4', count: '366',
      addr: '25 W Castillo Dr', q: 'Project Swing Park St Augustine', pid: 'ChIJVfknmr8n5IgRolaYSlS6anc',
      lat: 29.8981986, lng: -81.316876, walk: '1-min walk', dur: '20 min' },

    { t: '6:15', tags: ['history'], name: 'Oldest Wooden Schoolhouse', type: 'History \u00b7 quick',
      what: '1700s classroom on St. George. Open till 8 on Fri and Sat.',
      blurb: 'Small, self-guided, done in half an hour. The desks and the garden out back land better with kids than you would expect.',
      hours: '10:00 AM \u2013 8:00 PM Fri &amp; Sat', price: 'Small admission, roughly $7 adult',
      rating: '4.6', count: '172', addr: '14 St George St', phone: '9048240192',
      q: 'Oldest Wooden Schoolhouse St Augustine', pid: 'ChIJA3Lga74n5IgRIwMbEHqTHQM',
      lat: 29.8973365, lng: -81.3135519, walk: '5-min walk', dur: '30 min' },

    { t: '7:00', tags: ['food'], name: "Pizzalley's", type: 'Dinner',
      what: 'Pizza and pasta on St. George. Cheap, fast, no bar scene.',
      blurb: 'Huge portions and no wait, unlike the places with live music. A 10-inch splits fine between two kids.',
      hours: '11:30 AM \u2013 8:30 PM', price: '$', rating: '4.4', count: '1,088',
      addr: '117 St George St', phone: '9048252627', q: 'Pizzalleys on St George St Augustine',
      pid: 'ChIJL7xS4JUn5IgR12J0Ib8SrSc', lat: 29.8942136, lng: -81.3127829, walk: '4-min walk', dur: '60 min',
      alts: [{ n: 'Casa Maya', d: 'Mexican, covered patio, good with allergies \u00b7 4.3 (3,340)', q: 'Casa Maya St Augustine', id: 'ChIJofgqBJYn5IgRVa-HQvp6KDk' },
        { n: 'Prohibition Kitchen', d: 'Gastropub, live music \u00b7 4.4 (7,691) \u00b7 can be a long wait', q: 'Prohibition Kitchen St Augustine', id: 'ChIJC2do4JUn5IgRuCCaO-aklds' },
        { n: "The Backyard at Meehan's", d: 'Bayfront patio, fire pits \u00b7 4.5 (565)', q: 'The Backyard at Meehans St Augustine', id: 'ChIJp18zNwEn5IgRYOAfGVSw4XI' }] },

    { t: '8:15', tags: ['kids', 'food'], name: 'Kilwins', type: 'Ice cream',
      what: 'On the walk back up St. George.',
      blurb: 'Waffle cones made in the window, at the top end near the City Gate. You are already walking past it.',
      hours: '10:00 AM \u2013 10:00 PM Fri', price: '$', rating: '4.4', count: '292',
      addr: '6 St George St', phone: '9048239226', q: 'Kilwins St George Street St Augustine',
      pid: 'ChIJhWCYaL4n5IgRZ5rTA9gxkxA', lat: 29.8975215, lng: -81.3136587, walk: '6-min walk', dur: '20 min',
      alts: [{ n: 'The Hyppo', d: 'Gourmet ice pops, many dairy-free \u00b7 till 11 PM \u00b7 4.8 (1,151)', q: 'The Hyppo Gourmet Ice Pops St Augustine', id: 'ChIJQeGGBpYn5IgRYtLyxa40ofc' }] }
  ]},

  { id: 'sat', label: 'Sat \u00b7 full day',
    note: 'Fort at opening, living-history tour at 10:30, lunch inside a landmark. Afternoon is pool and AC, evening is the pirate ship.',
    stops: [
    { t: '8:00', key: 1, tags: ['food'], name: 'Maple Street Biscuit Co.', type: 'Breakfast \u00b7 chicken &amp; waffles',
      what: 'Chicken and waffles, biscuit sandwiches, bonuts.',
      blurb: 'Order at the counter, sit anywhere, the cook brings it out. They will cook the waffles soft if the kids do not like them crispy.',
      hours: 'Opens around 7 AM \u2014 confirm in Maps first', price: '$$', rating: '4.5', count: '3,402',
      addr: '39 Cordova St', phone: '9042177814', q: 'Maple Street Biscuit Company St Augustine',
      pid: 'ChIJ16XdhpUn5IgRog_yANrex8Q', lat: 29.8952259, lng: -81.3145454, walk: '4-min walk', dur: '55 min',
      flag: 'Their hours were not published \u2014 check the Maps listing before you walk over.',
      alts: [{ n: 'Harbor View Caf\u00e9', d: 'Waffles on the water \u00b7 7 AM\u20132 PM \u00b7 4.4 (1,087)', q: 'Harbor View Cafe St Augustine', id: 'ChIJEwIeH5Yn5IgRlSLo50SFDI0' },
        { n: "Georgie's Diner", d: 'Yesterday\u2019s diner, if it was a hit \u00b7 7 AM\u20133 PM', q: 'Georgies Diner St Augustine', id: 'ChIJywhop-sn5IgR2FX_DJgy8w8' },
        { n: 'The Kookaburra', d: 'Coffee and pastry only, if you want the fort by 9', q: 'The Kookaburra Downtown St Augustine', id: 'ChIJs-j0fpYn5IgRDCh5tKV1Obc' }] },

    { t: '9:00', key: 1, tags: ['history', 'kids'], name: 'Castillo de San Marcos', type: 'The main event',
      what: '1695 Spanish fort. Never taken by force. Cannon firings on weekends.',
      blurb: 'Coquina walls, the whole bay from the gun deck, self-guided so you set the pace. Go at opening \u2014 there is no shade up top by 11.',
      hours: '9:00 AM \u2013 5:00 PM \u00b7 last admission 4:45',
      price: '$30 adult \u00b7 15 and under free \u00b7 pass good 7 days', rating: '4.7', count: '38,320',
      addr: '11 S Castillo Dr', phone: '9048296506', q: 'Castillo de San Marcos',
      pid: 'ChIJH6jzd74n5IgRsYpaqo4LwNk', lat: 29.8978618, lng: -81.3115187, walk: '5-min walk', dur: '75 min',
      flag: 'Cannon demonstrations run Fri\u2013Sun but times shift. Call 904-829-6506 before promising the kids.' },

    { t: '10:30', key: 1, tags: ['history', 'kids'], name: 'Colonial Quarter', type: 'History the kids like',
      what: 'Living-history tour: blacksmith, musket firing, watchtower.',
      blurb: 'Guided tour roughly on the half hour \u2014 10:30, 12:00, 1:30 and 3:00 \u2014 about an hour, ending with a musket demonstration. The guides do the heavy lifting.',
      hours: '10:00 AM \u2013 5:00 PM', price: 'About $16 adult \u00b7 $10 kids 5\u201315 \u00b7 4 and under free',
      rating: '4.6', count: '505', addr: '14 S Castillo Dr', phone: '9043422869',
      q: 'Colonial Quarter St Augustine', pid: 'ChIJaXSQbL4n5IgR41hDG9udv2o',
      lat: 29.8967467, lng: -81.3129109, walk: '2-min walk', dur: '60 min',
      flag: 'Confirm the 10:30 tour is running when you buy \u2014 tour times move in summer.' },

    { t: '12:00', tags: ['food', 'history'], name: 'Columbia Restaurant', type: 'Lunch \u00b7 also a landmark',
      what: 'Spanish tiles, 1905 salad tossed at the table.',
      blurb: "Florida's oldest restaurant family, and the room is worth the stop on its own. Lunch is far easier to get into than dinner \u2014 call ahead and arrive ten minutes early.",
      hours: '11:00 AM \u2013 10:00 PM', price: '$$ \u00b7 tapas share well with kids', rating: '4.4', count: '14,193',
      addr: '98 St George St', phone: '9048243341', q: 'Columbia Restaurant St Augustine',
      pid: 'ChIJ8xR18JUn5IgRfwJJByM-quU', lat: 29.894835, lng: -81.313145, walk: '6-min walk', dur: '75 min',
      flag: 'Reserve ahead. Call 904-824-3341.',
      alts: [{ n: 'Casa Maya', d: 'Two minutes away, patio, careful with allergies \u00b7 4.3 (3,340)', q: 'Casa Maya St Augustine', id: 'ChIJofgqBJYn5IgRVa-HQvp6KDk' },
        { n: "Pizzalley's", d: 'If the kids want the known quantity again \u00b7 4.4 (1,088)', q: 'Pizzalleys on St George St Augustine', id: 'ChIJL7xS4JUn5IgR12J0Ib8SrSc' },
        { n: 'Prohibition Kitchen', d: 'Big menu, big room \u00b7 4.4 (7,691) \u00b7 expect a wait at noon', q: 'Prohibition Kitchen St Augustine', id: 'ChIJC2do4JUn5IgRuCCaO-aklds' }] },

    { t: '1:20', tags: ['history', 'free'], name: 'Plaza &amp; Cathedral Basilica', type: 'City walk \u00b7 free',
      what: 'Oldest parish in the country, on the oldest public square.',
      blurb: 'Fifteen minutes inside, free, directly on the walk south. Shaded benches on the Plaza if anyone needs to sit down.',
      hours: '8:00 AM \u2013 5:00 PM', price: 'Free \u00b7 donations welcome', rating: '4.8', count: '3,451',
      addr: '38 Cathedral Pl', phone: '9048242806', q: 'Cathedral Basilica of St Augustine',
      pid: 'ChIJw5kQd5Yn5IgRZWp4aEBLGmg', lat: 29.8931252, lng: -81.3123911, walk: '3-min walk', dur: '30 min' },

    { t: '1:50', tags: ['free', 'history'], name: 'Aviles Street', type: 'City walk \u00b7 free',
      what: 'Oldest street in the United States. Nobody is on it.',
      blurb: 'One block south of the Plaza \u2014 narrow, shaded, galleries and courtyards, and a fraction of the St. George crowd.',
      hours: 'Always open', price: 'Free', addr: 'Aviles St', q: 'Aviles Street St Augustine',
      lat: 29.892, lng: -81.3117, walk: '2-min walk', dur: '25 min' },

    { t: '2:20', opt: 1, tags: ['coffee', 'rest'], name: 'The Hyppo', type: 'Cool-down stop',
      what: 'Gourmet ice pops, lots of dairy-free. On the walk back.',
      blurb: 'Real-fruit pops with unusual flavour combinations, and plenty that skip dairy entirely.',
      hours: '11:00 AM \u2013 11:00 PM Sat', price: '$', rating: '4.8', count: '1,151',
      addr: '48 Charlotte St', phone: '9047920374', q: 'The Hyppo Gourmet Ice Pops St Augustine',
      pid: 'ChIJQeGGBpYn5IgRYtLyxa40ofc', lat: 29.8951251, lng: -81.3119505, walk: '4-min walk', dur: '20 min' },

    { t: '2:45', opt: 1, tags: ['rest'], name: 'Pool \u00b7 AC', type: 'Rest stop',
      what: 'Out of the sun through the worst of the afternoon.',
      blurb: 'This block is what makes the evening possible. Storms usually roll through between 1 and 4 anyway.',
      hours: '\u2014', price: '\u2014', addr: 'Downtown', q: 'Castillo Dr St Augustine',
      lat: 29.8992, lng: -81.3158, walk: '5-min walk', dur: '60 min' },

    { t: '4:00', key: 1, tags: ['kids'], name: 'Black Raven pirate ship', type: 'Biggest kid moment',
      what: 'Sword fights, cannons, treasure. 90 min on the water.',
      blurb: 'A real ship with a cast that works the kids the whole sail. Book the family Treasure Hunt, not the 21+ Rum Runner. Leave 25 minutes early \u2014 it is a 15-minute walk to the marina.',
      hours: 'Sailings 1:00 PM and 4:00 PM through Aug 14',
      price: '$44.95 adult \u00b7 $39.95 child 3\u201312 \u00b7 $12.95 under 3', rating: '4.4', count: '1,219',
      addr: '111 Avenida Menendez \u2014 Municipal Marina', phone: '9048260000',
      q: 'Black Raven Pirate Ship St Augustine', pid: 'ChIJVVyd-ZYn5IgRYT-Ia-TCB_8',
      lat: 29.8917553, lng: -81.3104262, walk: '15-min walk', dur: '90 min',
      flag: 'Sells out. If the 1:00 PM sailing is open, take it \u2014 the whole afternoon opens up.' },

    { t: '6:00', tags: ['food'], name: "Harry's Seafood", type: 'Dinner',
      what: 'Bayfront courtyard, three minutes from the ship.',
      blurb: 'Cajun-leaning seafood in a walled courtyard with live music. Ask for the courtyard or the bay room, not the back room by the restrooms.',
      hours: '11:00 AM \u2013 11:00 PM Sat', price: '$$', rating: '4.6', count: '16,043',
      addr: '46 Avenida Menendez', phone: '9048247765', q: 'Harrys Seafood Bar and Grille St Augustine',
      pid: 'ChIJ8aLBaJYn5IgR60p2CS_RHIw', lat: 29.893406, lng: -81.3113053, walk: '3-min walk', dur: '75 min',
      alts: [{ n: "The Backyard at Meehan's", d: 'Two doors down, patio and fire pits \u00b7 4.5 (565)', q: 'The Backyard at Meehans St Augustine', id: 'ChIJp18zNwEn5IgRYOAfGVSw4XI' },
        { n: 'Casa Maya', d: 'Mexican, 5-min walk inland \u00b7 4.3 (3,340)', q: 'Casa Maya St Augustine', id: 'ChIJofgqBJYn5IgRVa-HQvp6KDk' },
        { n: 'Columbia', d: 'If lunch went well and you want the room again \u00b7 4.4 (14,193)', q: 'Columbia Restaurant St Augustine', id: 'ChIJ8xR18JUn5IgRfwJJByM-quU' }] },

    { t: '7:30', opt: 1, tags: ['free', 'rest'], name: 'Seawall walk home', type: 'Free',
      what: 'Along the bay, past the Bridge of Lions.',
      blurb: 'Ten minutes, flat, breeze off the water, and the fort lit up at the end of it. Best free thing in town.',
      hours: 'Always open', price: 'Free', addr: 'Avenida Menendez seawall',
      q: 'Bridge of Lions St Augustine', lat: 29.8925, lng: -81.3105, walk: '12-min walk', dur: '25 min' }
  ]}
]};
