/* Old Town Trolley \u2014 all 22 stops, transcribed from the printed route map.
 * Coordinates for the major landmarks are exact; the smaller stops are placed
 * to the corner the trolley actually pulls up at, so treat them as close but
 * not survey-grade.
 * tip = why you personally would or would not get off here.
 */
window.TROLLEY = {
  name: 'Old Town Trolley',
  note: 'Hop on and off all day at 22 stops. Last trolley out is 4:30 PM. Stop 1 (Old Jail) has ' +
    'free parking and throws in the History Museum; stop 14 is where the free Beach Bus leaves for ' +
    'the Alligator Farm and the beach.',
  stops: [
  { n: 1, name: 'Old Town \u00b7 The Old Jail', what: 'Old Jail, History Museum, Oldest Store Museum, Gator Bob\u2019s, Spice & Tea Exchange',
    tip: 'Start here if you drive: free parking, trolleys leave empty so you always get a seat, and your ticket includes the History Museum. A mile north of the historic core though.',
    perks: 'Free parking \u00b7 Free History Museum', lat: 29.9057, lng: -81.3235 },
  { n: 2, name: 'Visitor Information Center', what: 'Tickets, restrooms, Nights of Lights boarding',
    tip: 'Your closest boarding point \u2014 one block from the hotel. Restrooms and the garage are here too.',
    perks: 'Parking \u00b7 Tickets', lat: 29.8985, lng: -81.3163 },
  { n: 3, name: 'Old Drug Store', what: 'Potter\u2019s Wax Museum, Tolomato Cemetery',
    tip: 'Tolomato is the oldest cemetery in the state and free to look at through the gates. Wax museum is skippable.',
    perks: 'Discount parking', lat: 29.8977, lng: -81.3151 },
  { n: 4, name: 'City Gates \u00b7 St. George Street', what: 'The pedestrian walking mall, Oldest Wooden School House',
    tip: 'This is where your walk starts. If you only get off once, get off here.',
    lat: 29.8977, lng: -81.3136 },
  { n: 5, name: 'Colonial Quarter', what: 'Colonial Quarter, Pirate & Treasure Museum, Castillo de San Marcos',
    tip: 'Three of your must-dos at one stop. Saturday morning this is the whole plan.',
    lat: 29.8968, lng: -81.3129 },
  { n: 6, name: 'Bay View', what: 'Bayfront at the Best Western',
    tip: 'Nothing to do here. Stay on.', lat: 29.8955, lng: -81.3105 },
  { n: 7, name: 'Hypolita & St. George', what: 'Shipwreck Museum, Medieval Torture Museum',
    tip: 'Shipwreck Museum is real pirate salvage and works for kids. The Torture Museum is graphic \u2014 not for young children.',
    lat: 29.895, lng: -81.3128 },
  { n: 8, name: 'The three churches', what: 'Flagler Memorial Presbyterian, Grace United Methodist, Ancient City Baptist',
    tip: 'Flagler Memorial is a Venetian Renaissance dome and holds Flagler\u2019s tomb. Worth a look from the pavement, five minutes.',
    lat: 29.893, lng: -81.316 },
  { n: 9, name: 'Villa Zorayda Museum', what: '1883 Moorish palace, self-guided audio tour',
    tip: 'Your second castle. About an hour, 4.6 stars, closes at 5.', lat: 29.8916, lng: -81.3151 },
  { n: 10, name: 'Lightner Museum \u00b7 Flagler College', what: 'Two Gilded Age hotels facing each other',
    tip: 'Flagler lobby is free. Lightner is the best rainy-afternoon backup in the city and kids under 12 are free.',
    lat: 29.8909, lng: -81.3136 },
  { n: 11, name: 'Lincolnville Museum', what: 'African American history and civil rights in St. Augustine',
    tip: 'The city\u2019s civil rights history, in the neighbourhood where it happened. Includes a complimentary walking tour.',
    perks: 'Free walking tour', lat: 29.8877, lng: -81.3168 },
  { n: 12, name: 'St. Augustine Distillery', what: 'Free tours and tastings',
    tip: 'Adults only in practice. Skip on a kid day.', lat: 29.8905, lng: -81.3225 },
  { n: 13, name: 'San Sebastian Winery \u00b7 Whetstone Chocolates', what: 'Winery tour and the chocolate factory tour',
    tip: 'Whetstone was already on your list. Chocolate tour plus a winery in one stop is the best adult-and-kid compromise on the route.',
    lat: 29.8912, lng: -81.3243 },
  { n: 14, name: 'Plaza de la Constituci\u00f3n', what: 'Government House, Cathedral Basilica, Pe\u00f1a-Peck House',
    tip: 'The oldest public square in the country, and the FREE BEACH BUS leaves from here to the Alligator Farm and the beach. That is the Sunday move.',
    perks: 'Beach Bus \u00b7 Free walking tour', lat: 29.8925, lng: -81.3128 },
  { n: 15, name: 'Municipal Marina', what: 'Black Raven, Schooner Freedom, Scenic Cruise, Spanish Military Hospital, Xim\u00e9nez-Fatio House',
    tip: 'Where the pirate ship sails from. Get off here Saturday afternoon.', lat: 29.8917, lng: -81.311 },
  { n: 16, name: 'Oldest House', what: 'Gonz\u00e1lez-\u00c1lvarez House, Fernandez-Llambias House',
    tip: 'Oldest surviving house in Florida. Quiet, quick, and nobody is ever there.', lat: 29.8885, lng: -81.3115 },
  { n: 17, name: 'Castillo de San Marcos', what: 'The fort',
    tip: 'Includes a complimentary walking tour. Two minutes from your hotel on foot anyway.',
    perks: 'Free walking tour', lat: 29.8979, lng: -81.3115 },
  { n: 18, name: 'Ripley\u2019s Believe It or Not!', what: 'Ripley\u2019s, Red Train Tours',
    tip: 'The competing tour company and an oddities museum. Fine in rain, otherwise skip.', lat: 29.8994, lng: -81.3178 },
  { n: 19, name: 'Trolley Welcome Center', what: 'Ghosts & Gravestones, Uptown San Marco shopping',
    tip: 'Discount parking with a tour ticket. The ghost tour is a night thing and too scary for small kids.',
    perks: 'Discount parking', lat: 29.8999, lng: -81.32 },
  { n: 20, name: 'Mission of Nombre de Dios', what: 'Shrine of Our Lady of La Leche, the great cross',
    tip: 'Where the first Mass in the country was said, 1565. Free, waterfront, calm. Sunday hours are only 12\u20134.',
    lat: 29.9028, lng: -81.314 },
  { n: 21, name: 'The Old Senator \u00b7 Villa 1565', what: 'A 600-year-old live oak',
    tip: 'A very old tree. Nice from the trolley window, not worth a stop.', lat: 29.9046, lng: -81.3179 },
  { n: 22, name: 'Fountain of Youth', what: '1565 founding site, peacocks, cannon firings, planetarium',
    tip: 'Your Sunday option C, and the only anchor that is not across the bridge. Two hours, mostly outdoors.',
    lat: 29.9069, lng: -81.315 }
]};
